name: oj

on: [push, pull_request]

jobs:
  oj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper
      - name: Run tests
        run: |
          oj-verify run
