name: Unittest

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  gtest:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run unittest
        run: |
          mkdir build
          cd build
          cmake ../test -DCMAKE_BUILD_TYPE=Debug
          make
          ctest -VV
        env:
          GTEST_COLOR: "1"
