name: Unittest

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  gtest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        avx2: [ON, OFF]

    steps:
      - uses: actions/checkout@v4
      - name: run unittest
        run: |
          mkdir build
          cd build
          cmake ../test -DCMAKE_BUILD_TYPE=Debug -DAVX2=${{ matrix.avx2 }}
          make
          ./unittest
        env:
          GTEST_COLOR: "1"
